### ISSUE TITLE
change MQTT device tracker state to either 'home' or 'away'

### ISSUE THREAD

**Issue by fama-lama** [jokob-sk/NetAlertX#702]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

the state of the device tracker is currently
{"is_present": "ON"} or {"is_present": "OFF"}

![Screenshot from 2024-06-11 16-43-37](https://github.com/jokob-sk/NetAlertX/assets/110621069/63c51722-e8ca-433f-8c19-a8400ebe2c22)

### Expected Behavior

This is the same device using a different integration ([https://github.com/mudape/iphonedetect](url))

![Screenshot from 2024-06-11 16-43-13](https://github.com/jokob-sk/NetAlertX/assets/110621069/d88ee576-a0ec-4537-917e-1f7d3e5887db)

it shows the device as either 'home' or 'away'.

### Steps To Reproduce

1. presence sensor type: DEVICE_TRACKER
2. connect Home Assistant and NetAlertX to the same mqtt broker.

### app.conf

```python
# MQTT
#---------------------------
MQTT_RUN='schedule'
MQTT_RUN__metadata="{\"function\": \"RUN\", \"events\": [\"test\"], \"type\": \"text.select\", \"default_value\": \"disabled>
MQTT_CMD='python3 /app/front/plugins/_publisher_mqtt/mqtt.py devices={devices}'
MQTT_CMD__metadata="{\"function\": \"CMD\", \"type\": \"readonly\", \"default_value\": \"python3 /app/front/plugins/_publish>
MQTT_RUN_SCHD='*/5 * * * *'
MQTT_RUN_SCHD__metadata="{\"function\": \"RUN_SCHD\", \"type\": \"text\", \"default_value\": \"0 2 * * 3\", \"options\": [],>
MQTT_RUN_TIMEOUT=20
MQTT_RUN_TIMEOUT__metadata="{\"function\": \"RUN_TIMEOUT\", \"type\": \"integer\", \"default_value\": 20, \"options\": [], \>
MQTT_BROKER='192.168.100.55'
MQTT_BROKER__metadata="{\"function\": \"BROKER\", \"type\": \"text\", \"default_value\": \"\", \"options\": [], \"localized\>
MQTT_PORT=1883
MQTT_PORT__metadata="{\"function\": \"PORT\", \"type\": \"integer\", \"default_value\": 1883, \"options\": [], \"localized\">
MQTT_USER='hREDACTED'
MQTT_USER__metadata="{\"function\": \"USER\", \"type\": \"text\", \"default_value\": \"\", \"options\": [], \"localized\": [>
MQTT_PASSWORD='REDACTED'
MQTT_PASSWORD__metadata="{\"function\": \"PASSWORD\", \"type\": \"password\", \"default_value\": \"\", \"options\": [], \"lo>
MQTT_SEND_STATS=True
MQTT_SEND_STATS__metadata="{\"function\": \"SEND_STATS\", \"type\": \"boolean\", \"default_value\": true, \"options\": [], \>
MQTT_DEVICE_ID='netalertx'
MQTT_DEVICE_ID__metadata="{\"function\": \"DEVICE_ID\", \"type\": \"text\", \"default_value\": \"netalertx\", \"options\": [>
MQTT_DEVICE_NAME='netalertx'
MQTT_DEVICE_NAME__metadata="{\"function\": \"DEVICE_NAME\", \"type\": \"text\", \"default_value\": \"NetAlertX\", \"options\>
MQTT_SEND_DEVICES=True
MQTT_SEND_DEVICES__metadata="{\"function\": \"SEND_DEVICES\", \"type\": \"boolean\", \"default_value\": true, \"options\": [>
MQTT_PRESENCE_SENSOR_TYPE='device_tracker'
MQTT_PRESENCE_SENSOR_TYPE__metadata="{\"function\": \"PRESENCE_SENSOR_TYPE\", \"events\": [], \"type\": \"text.select\", \"d>
MQTT_QOS=0
MQTT_QOS__metadata="{\"function\": \"QOS\", \"type\": \"integer.select\", \"default_value\": 0, \"options\": [0, 1, 2], \"lo>
MQTT_VERSION=1
MQTT_VERSION__metadata="{\"function\": \"VERSION\", \"type\": \"integer.select\", \"default_value\": 1, \"options\": [1, 2],>
MQTT_DELAY_SEC=2
MQTT_DELAY_SEC__metadata="{\"function\": \"DELAY_SEC\", \"type\": \"integer\", \"default_value\": 2, \"options\": [2, 3, 4, >
```

### docker-compose.yml

```python
version: "3.0"
services:
  netalertx:
    container_name: NetAlertX
    hostname: NetAlertX
    privileged: true
    user: 0:0
    image: jokobsk/netalertx-dev:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /opt/netalertx/config:/app/config
      - /opt/netalertx/db:/app/db
      - /opt/netalertx/logs:/app/front/log
    environment:
      - TZ=Asia/Singapore
      - PORT=20211
```

### What branch are you running?

Dev

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

👉If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved/the new feature is working.

⭐ This feature took 4h ⏳ to implement - consider becoming a sponsor ⭐

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/a31e634a-3269-4355-bbc5-95b8ff816300)


Thanks in advance,
j

**Comment by fama-lama** [comment]
Hi I updated netalertx-dev and when I ran the  matt plugin I get this error.

```
                                [2024-06-12_19-24-33] Log file manually purged
19:24:46 [2024-06-12 19:24:46+08:00] [Test] START Test: MQTT
19:24:46 [Notification] Open text Template
19:24:46 [Notification] Open html Template
19:24:46 [Notification] Using template/app/front/report_templates/report_template.html
19:24:46 [Notification] New Devices sections done.
19:24:46 [Notification] Down Devices sections done.
19:24:46 [Notification] Reconnected Down Devices sections done.
19:24:46 [Notification] Events sections done.
19:24:46 [Notification] Plugins sections done.
19:24:46 [Send API] Updating notification_* files in /app/front/api/
19:24:46 [Notification] Udating API files
19:24:46 [2024-06-12 19:24:46+08:00] START Run: MQTT
19:24:46 [Plugins] Executing: python3 /app/front/plugins/_publisher_mqtt/mqtt.py devices={devices}
19:24:46 [MQTT](publisher) In script
19:24:46 [Database] Opening DB
19:24:46 [MQTT]         Connected to broker
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Sending MQTT topic: system-sensors/sensor/netalertx/state
19:24:46 [MQTT] Sending MQTT message: {"online": 42, "down": 15, "all": 57, "archived": 0, "new": 7, "unknown": 7}
19:24:46 [MQTT]         Estimated delay: 570s (9.5min)
19:24:46 [MQTT] Existing, skip Device Name    : Internet
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [Plugin utils] 💬 INFO - Object not found {"Plugin": "MQTT", "Watched_Value3": "a9127ee4e5b7b5983b657476dc94d635"} 
19:24:46 [MQTT] New sensor entry name         : Internet
19:24:47 /app/front/plugins/_publisher_mqtt/mqtt.py:357: SyntaxWarning: invalid escape sequence '\s'
  devDisplayName  = re.sub('[^a-zA-Z0-9-_\s]', '', device["dev_Name"]) 
/app/front/plugins/_publisher_mqtt/mqtt.py:288: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  mqtt_client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
[plugin_helper] reading config file
19:24:46 [MQTT](publisher) In script
19:24:46 [Database] Opening DB
19:24:46 [MQTT]         Connected to broker
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Existing, skip Device Name    : netalertx
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [MQTT] Sending MQTT topic: system-sensors/sensor/netalertx/state
19:24:46 [MQTT] Sending MQTT message: {"online": 42, "down": 15, "all": 57, "archived": 0, "new": 7, "unknown": 7}
19:24:46 [MQTT]         Estimated delay: 570s (9.5min)
19:24:46 [MQTT] Existing, skip Device Name    : Internet
19:24:46 [MQTT] Publishing sensor number 0
19:24:46 [Plugin utils] 💬 INFO - Object not found {"Plugin": "MQTT", "Watched_Value3": "a9127ee4e5b7b5983b657476dc94d635"} 
19:24:46 [MQTT] New sensor entry name         : Internet
Traceback (most recent call last):
  File "/app/front/plugins/_publisher_mqtt/mqtt.py", line 428, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/front/plugins/_publisher_mqtt/mqtt.py", line 63, in main
    mqtt_start(db)
  File "/app/front/plugins/_publisher_mqtt/mqtt.py", line 360, in mqtt_start
    sensorConfig = create_sensor(mqtt_client, deviceId, devDisplayName, 'sensor', 'mac_address', 'folder-key-network', device["dev_MAC"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/front/plugins/_publisher_mqtt/mqtt.py", line 245, in create_sensor
    sensorConfig = sensor_config(deviceId, deviceName, sensorType, sensorName, icon, mac) 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/front/plugins/_publisher_mqtt/mqtt.py", line 161, in __init__
    mylog('verbose', [f"[{pluginName}] New sensor entry mac          : {self.mac}"])  
                                                                        ^^^^^^^^
AttributeError: 'sensor_config' object has no attribute 'mac'

19:24:47 [Plugins] ⚠ ERROR - enable LOG_LEVEL=debug and check logs
19:24:47 [Plugins] No output received from the plugin MQTT - enable LOG_LEVEL=debug and check logs
19:24:47 [2024-06-12 19:24:47+08:00] END Run: MQTT
19:24:47 [Test] END Test: MQTT
                              
```

**Comment by jokob-sk** [comment]
Thanks for testing this so quickly - I'm pushing a new version which should hopefully fix this. A new image will be ready in ~15 min

**Comment by fama-lama** [comment]
Fixed! Beautiful. Thanks Jacob 

I noticed you changed naming scheme to "device_tracker.X_is_home"
Is it safe to delete the "device_tracker.X_is_present" entities?

**Comment by fama-lama** [comment]
Hey, is it possible to remove the quotation marks for "home" and "away"?

**Comment by Ey3scr34m** [comment]
Unfortunately it still shows as "home" instead of home.

**Comment by jokob-sk** [comment]
@Ey3scr34m not sure what to change then as I think I'm following the docs... Any ideas?

**Comment by jokob-sk** [comment]
I've posted on the HA forum, so let's see if I can get help from there: https://community.home-assistant.io/t/removing-quotes-from-mqtt-device-tracker-state/739263

**Comment by jokob-sk** [comment]
Hey @fama-lama & @Ey3scr34m - no one is replying on the HA forums so not sure if it's possible. If you have any ideas, let me know, but I'm not getting any traction on their forum and it's been 2 weeks.

**Comment by ingoratsdorf** [comment]
Hi,
I know this is closed but I stumpled across the same issue, trying to replace the TP-Link Deco integration in HA with NetAlertX.

I had a look in Cedalo Management centre for Eclipse Mosquitto and the payload is in there already wrong.
Other sensors I compared it to had `home` or `online` in the payload, NetAlertX has `"home"`.
So somewhere when you are publishing the payload to MQTT, you are publishing the quotes into it.

I'll have a look in your source code and see if I can spot something.

**Comment by jokob-sk** [comment]
Thanks in advance, didn't get any answer in the HA forum.

**Comment by ingoratsdorf** [comment]
Found the issue.

```
def publish_mqtt(mqtt_client, topic, message):
    status = 1

    message = json.dumps(message).replace("'",'"')
```

`publish_mqtt` expects a dict and transforms it into a json dump for publishing, but you are only publishing a string `home`.

```
def mqtt_start(db):   
[..]
            # <away|home> are only valid states
            state = 'away'
            if to_binary_sensor(str(device["dev_PresentLastScan"])) == "ON":
                state = 'home'

            publish_mqtt(mqtt_client, sensorConfig.state_topic, state) 
```

`json_dumps` adds quotations to the string:

```
>>> import json
>>> json.dumps("home")
'"home"'
>>>
```

So we either need to stick to json only or check the instance and if the instance is just a string, then do not do any `json_dumps`.

Happy to debug and fix. Could we please reopen this?

**Comment by jokob-sk** [comment]
Thanks a lot @ingoratsdorf 🙏 this was driving me crazy

**Comment by jokob-sk** [comment]
Releasing -> closing
