### ISSUE TITLE
[bug] Persistent notification - Cause: Integer name casues backend restart

### ISSUE THREAD

**Issue by sk8er000** [jokob-sk/NetAlertX#874]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [X] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

Opening the web interface from the browser it appears the following notification:

[Upgrade] : App upgraded 🚀 Please clear the cache:

    Click OK below
    Clear the browser cache (shift + browser refresh button)
    Clear app cache with the 🔄 (reload) button in the header
    Go to Settings and click Save

Check out new features and what has changed in the [📓 release notes](https://github.com/jokob-sk/NetAlertX/releases).

But after doing every step multiple times the notification still pops up.

### Expected Behavior

The notification should disappear after doing all the steps

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @sk8er000,

Please submit your log. I sent help otherwise. This is usually happening because the backend is restarting.

https://github.com/jokob-sk/NetAlertX/issues/811

Thanks,
J

**Comment by jokob-sk** [comment]
Sure, even better if you only share the part of your logs with the exception, just before the backend restarted.

You might need to check Portainer to get these exceptions.

See these guides for additional details:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_PLUGINS.md

https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md

**Comment by sk8er000** [comment]
Thank you very much, I've sent the log to your email address if they are too big as soon as I come back tonight I'll try to locate the important part and paste it here

**Comment by jokob-sk** [comment]
Haven't received anything so far.

**Comment by sk8er000** [comment]
I've sent the log with my gmail to the mail reported on the previous links

**Comment by sk8er000** [comment]
is this part?

> 2024-11-05T11:45:55.112584561Z 12:45:55 [New Devices] New Devices end
2024-11-05T11:45:55.112587600Z 12:45:55 [Process Scan] Updating Devices Info
2024-11-05T11:45:55.112590631Z 12:45:55 [Update Devices] 1 Last Connection
2024-11-05T11:45:55.112593607Z 12:45:55 [Update Devices] 2 Clean no active devices
2024-11-05T11:45:55.131888609Z Traceback (most recent call last):
2024-11-05T11:45:55.131917459Z   File "<frozen runpy>", line 198, in _run_module_as_main
2024-11-05T11:45:55.131920817Z   File "<frozen runpy>", line 88, in _run_code
2024-11-05T11:45:55.131922970Z   File "/app/server/__main__.py", line 209, in <module>
2024-11-05T11:45:55.132046807Z     sys.exit(main())       
2024-11-05T11:45:55.132076663Z              ^^^^^^
2024-11-05T11:45:55.132080690Z   File "/app/server/__main__.py", line 139, in main
2024-11-05T11:45:55.132260120Z     process_scan(db)
2024-11-05T11:45:55.132332151Z   File "/app/server/networkscan.py", line 45, in process_scan
2024-11-05T11:45:55.132535771Z     update_devices_data_from_scan (db)
2024-11-05T11:45:55.132607959Z   File "/app/server/device.py", line 478, in update_devices_data_from_scan
2024-11-05T11:45:55.132903336Z     dev_DeviceType = guess_type(device['dev_Vendor'], device['dev_MAC'], device['dev_LastIP'], device['dev_Name'], default_type)
2024-11-05T11:45:55.133026824Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-05T11:45:55.133034496Z   File "/app/server/device.py", line 742, in guess_type
2024-11-05T11:45:55.133505555Z     name   = name.lower() if name else "(unknown)"
2024-11-05T11:45:55.133636811Z              ^^^^^^^^^^
2024-11-05T11:45:55.133645025Z AttributeError: 'int' object has no attribute 'lower'
2024-11-05T11:45:55.133762120Z 12:45:55 [Update Devices] - cur_IP -> dev_LastIP (always updated)
2024-11-05T11:45:55.133773169Z 12:45:55 [Update Devices] - cur_Vendor -> (if empty) dev_Vendor
2024-11-05T11:45:55.133777675Z 12:45:55 [Update Devices] - (if not empty) cur_Port -> dev_Network_Node_port
2024-11-05T11:45:55.133781330Z 12:45:55 [Update Devices] - (if not empty) cur_NetworkNodeMAC -> dev_Network_Node_MAC_ADDR
2024-11-05T11:45:55.133785396Z 12:45:55 [Update Devices] - (if not empty) cur_NetworkSite -> (if empty) dev_NetworkSite
2024-11-05T11:45:55.133807105Z 12:45:55 [Update Devices] - (if not empty) cur_SSID -> (if empty) dev_SSID
2024-11-05T11:45:55.133812097Z 12:45:55 [Update Devices] - (if not empty) cur_Type -> (if empty) dev_DeviceType
2024-11-05T11:45:55.133815991Z 12:45:55 [Update Devices] - (if not empty) cur_Name -> (if empty) dev_NAME
2024-11-05T11:45:56.286865915Z 
2024-11-05T11:45:56.286910588Z             [INSTALL] 🚀 Starting app (:20211)
2024-11-05T11:45:56.286917731Z 
2024-11-05T11:45:56.286922162Z         
2024-11-05T11:46:00.757894337Z 12:45:56 [MAIN] Setting up ...
2024-11-05T11:46:00.757916938Z 12:45:56 [conf.tz] Setting up ...
2024-11-05T11:46:00.757920989Z 12:45:56 
2024-11-05T11:46:00.757923155Z 
2024-11-05T11:46:00.757925018Z 12:45:56 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.
2024-11-05T11:46:00.757927121Z 12:45:56 
2024-11-05T11:46:00.757929488Z 
2024-11-05T11:46:00.757931414Z 12:45:56 Permissions check (All should be True)
2024-11-05T11:46:00.757933420Z 12:45:56 ------------------------------------------------
2024-11-05T11:46:00.757935413Z 12:45:56   /config/app.conf |  READ  | True
2024-11-05T11:46:00.757937276Z 12:45:56   /config/app.conf |  WRITE | True
2024-11-05T11:46:00.757939105Z 12:45:56   /db/app.db       |  READ  | True
2024-11-05T11:46:00.757940819Z 12:45:56   /db/app.db       |  WRITE | True
2024-11-05T11:46:00.757942699Z 12:45:56 ------------------------------------------------
2024-11-05T11:46:00.757944600Z 12:45:56 [Setup] Attempting to fix permissions.
2024-11-05T11:46:00.757946520Z 12:45:56 [Setup] Attempting to fix permissions.

**Comment by jokob-sk** [comment]
Thank you @sk8er000 ,

This is exactly what I needed. 

This should be fixed in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by sk8er000** [comment]
I'm sorry for the late reply, at the moment I can't easily access to my docker installation but I can try as soon as I can

**Comment by jokob-sk** [comment]
no rush @sk8er000 - thanks for the help 🙏

**Comment by sk8er000** [comment]
Sorry for the delay but I came back at night and went to sleep. I've redeployed my container using the dev branch. When I logged to the web I terface I received the same notification but after doing all the reported steps  it disappeared and now I can use the web interface! I'll try more deeply today and report here. In the meanwhile thank you very much for the prompt fix!

**Comment by jokob-sk** [comment]
No need to apologize and thanks for testing!

**Comment by sk8er000** [comment]
It's now a couple of days and didn't notice any issue with the actual dev branch image, I think that my issue is completely fixed.

Thank you! 🍻

**Comment by jokob-sk** [comment]
Hi @sk8er000 - glad to hear that and thanks for testing!

**Comment by jokob-sk** [comment]
Releasing -> Closing
